name: VoidLink CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Go
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.2'
          cache: true
          cache-dependency-path: go.sum

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: make unit-test

      - name: Build binary
        run: make build

      - name: Upload CLI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: voidlink
          path: ./vlink
          retention-days: 5

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: backend
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: voidlink

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          scp -i private_key -o StrictHostKeyChecking=no vlink $SSH_USER@$SSH_HOST:/home/$SSH_USER/vlink
          ssh -i private_key -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "chmod +x /home/$SSH_USER/vlink && sudo systemctl restart voidlink"
          rm private_key